ledger-configuration: Extract the configuration from participant-state. [KVL-1002]
digital-asset/daml pull request #10279
Opened 2021-07-14 13:42 UTC by SamirTalwar-DA

The configuration is often used without the state, and it probably doesn't need to be versioned in the same way.

This is a big PR. Apologies for that. It's pretty much entirely renames and repackaging; no behavior has changed except that we now publish an extra Maven package, _ledger-configuration_.

### Changelog

- **[Integration Kit]** The ledger configuration classes, `Configuration`, `LedgerInitialConditions`, and `TimeModel`, have been moved from _participant-state_ to a separate package named _ledger-configuration_, in the Java package `com.daml.ledger.configuration`. You will need to update your dependencies and imports.
- **[Integration Kit]** `TimeModel` has been renamed to `LedgerTimeModel`. If you are using the ledger configuration classes directly, you may need to update your code.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2021-07-14 13:42 UTC, SamirTalwar-DA commented
@gerolf-da, would you mind chiming in on whether this is a good idea or not?

2021-07-14 14:27 UTC, SamirTalwar-DA commented
To add a bit more context: the purpose of this is to decouple the _participant-state-index_ package from _participant-state_, so we can use v1 and v2 of the participant state interchangeably.

If this is acceptable, I will follow up with PRs to move `Offset` into a new package, and use the Daml-LF `Ref` object directly instead of the type aliases in _v1/package.scala_.

2021-07-14 14:54 UTC, hubert-da approved these changes
LGTM at a low level. You may want to wait for a higher level approval ;)

2021-07-14 14:54 UTC, hubert-da commented on ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v2/AdaptedV1ReadService.scala
> -  def adaptLedgerInitialConditions(
👍🏻

2021-07-14 14:54 UTC, hubert-da commented on ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v2/AdaptedV1WriteService.scala
> -  def adaptLedgerConfiguration(config: Configuration): v1.Configuration =
👍🏻

2021-07-14 16:02 UTC, gerolf-da requested changes
@SamirTalwar-DA: I'd like to understand the motivation for this change a bit better, please.

2021-07-14 16:08 UTC, miklos-da approved these changes

2021-07-15 07:34 UTC, SamirTalwar-DA commented
@gerolf-da: Happy to discuss any concerns here or over a call. :smiley:

2021-07-15 08:46 UTC, fabiotudone-da reviewed
I am not so confident about the ledger time model not having the same versioning model of the API, as it is (also) part of it; anyway, supposing we merge this change and then we need to start versioning it, how would you do it?

2021-07-15 08:46 UTC, fabiotudone-da commented on ledger/ledger-configuration/protobuf/ledger_configuration.rst
> +``com.daml.ledger.participant.state``.
I'd check usages and, if we can safely do it, I think it's better to do it (not necessarily as part of this PR).

2021-07-15 08:50 UTC, SamirTalwar-DA commented
@fabiotudone-da: The protobuf, _ledger_configuration.proto_, is versioned, which I think takes care of that problem. The classes can (I believe) be evolved safely, as long as they're always able to decode later versions of the protobuf.

Take a look at _Configuration.scala_. It has two `decode` methods, where v1 provides a sensible default for `maxDeduplicationTime`.

Do you think this satisfies your concern?

2021-07-15 08:53 UTC, rautenrieth-da reviewed
I had a quick high-level look at these changes.

My only concern was that now two different versions of the API (v1 and v2) depend on the same types, which means we'll have to be careful when changing those types (e.g., if `TimeModel` should change in v2 but not in v1). After discussion with @SamirTalwar-DA, I do not think this is an issue because:

1. We do not expect changes to the time model and the configuration
2. The v1 and v2 versions behave more like the stable and preview version of "the" participant state API, the main versioning of which is the SDK version.

2021-07-15 08:57 UTC, fabiotudone-da commented
> I had a quick high-level look at these changes.
> 
> My only concern was that now two different versions of the API (v1 and v2) depend on the same types, which means we'll have to be careful when changing those types (e.g., if `TimeModel` should change in v2 but not in v1). After discussion with @SamirTalwar-DA, I do not think this is an issue because:
> 
> 1. We do not expect changes to the time model and the configuration
> 2. The v1 and v2 versions behave more like the stable and preview version of "the" participant state API, the main versioning of which is the SDK version.

@SamirTalwar-DA @rautenrieth-da I think this satisfies my concerns. Thanks!

2021-07-15 08:57 UTC, fabiotudone-da approved these changes

2021-07-15 08:58 UTC, SamirTalwar-DA commented
OK, I'm going to merge this, with a bit of trepidation.

Worst-case scenario, we revert.

2021-07-15 13:03 UTC, merged

2021-07-15 16:19 UTC, SamirTalwar-DA commented on ledger/ledger-configuration/protobuf/ledger_configuration.rst
> +``com.daml.ledger.participant.state``.
#10302 covers this.