[JSON-API] Fix duplicate error logging & improve error logs messages
digital-asset/daml pull request #12906
Opened 2022-02-14 11:16 UTC by realvictorprm

That should improve the error logging situation further.

I manually tested:
- Errors from Futures

So a couple things here are changed with me only assuming that they do the right thing, however the code is very clear in this regard so I assume I'm right. Besides, testing all possible branches where errors could be generated is a bit time-consuming.

changelog_begin

- [HTTP-JSON] Fix duplicate logging of errors & improved error messages slightly

changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2022-02-14 19:18 UTC, S11001001 approved these changes

2022-02-16 10:06 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/CommandService.scala
> +  final case class InternalError(id: Option[Symbol], error: Throwable \/ String) extends Error
Is the throwable used in any way later? It would seem simpler to just take the String along.

2022-02-16 10:07 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/CommandService.scala
> +    def apply(id: Option[Symbol], error: Throwable): InternalError =
What if we just only kept the message of the error here, so `InternalError(id, error.message)`

2022-02-16 10:10 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +  final case class ServerError(message: Throwable \/ String) extends Error
Seems like a `String` should already do the trick?

2022-02-16 10:10 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +    def apply(error: Throwable): ServerError = ServerError(\/.left(error))
Here also just do `error.message`

2022-02-16 10:11 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +    def apply(error: Throwable): ServerError = ServerError(\/.left(error))
I might be missing something here, but a ServerError with a message or an error, they are both indicating an error, right? What is the distinction for?

2022-02-16 10:11 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +      case ServerError(e) => s"Endpoints.ServerError: ${e.fold(_.getMessage, identity): String}"
Since you always get the message out here, I don't think you need to track it in a disjunction

2022-02-16 10:12 UTC, ray-roestenburg-da requested changes
I might be misunderstanding, but I think it makes sense to just track the message, and not add a disjunction inside an error.

2022-02-16 10:17 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +        )
Here also the disjunction does not seem useful?

2022-02-16 10:17 UTC, realvictorprm commented
In short, my decision to do this was to preserve a proper logging of the
stack frame because it might seem like we always know where an error
origins from but it actually isn't for all kind of errors we weren't
expecting etc.

Raymond Roestenburg ***@***.***> schrieb am Mi., 16. Feb.
2022, 11:13:

> ***@***.**** requested changes on this pull request.
>
> I might be misunderstanding, but I think it makes sense to just track the
> message, and not add a disjunction inside an error.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/digital-asset/daml/pull/12906#pullrequestreview-884280523>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGB4Z4CXV22F2TIAADF2B6TU3N2CVANCNFSM5OLDWI5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-16 10:36 UTC, ray-roestenburg-da commented on ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> +        )
I think I would prefer to get the stacktrace string from Throwable in apply of `InternalError`, so you don't have to think about it later on.

2022-02-16 10:38 UTC, realvictorprm commented
I did that locally but the results were even less understandable code and
the log logged less good... Maybe it is better to just hand around
exceptions without throwing them as they automatically include the stack
trace if I understand things correctly

Raymond Roestenburg ***@***.***> schrieb am Mi., 16. Feb.
2022, 11:36:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala
> <https://github.com/digital-asset/daml/pull/12906#discussion_r807779906>:
>
> > @@ -317,7 +321,10 @@ object EndpointsCompanion {
>        case ParticipantServerError(grpcStatus, d) =>
>          grpcStatus.asAkkaHttpForJsonApi -> s"$grpcStatus${d.cata((": " + _), "")}"
>        case ServerError(reason) =>
> -        logger.error(s"Internal server error occured: $reason")
> +        reason.fold(
> +          logger.error(s"Internal server error occured", _),
> +          msg => logger.error(s"Internal server error occured: $msg"),
> +        )
>
> I think I would prefer to get the stacktrace string from Throwable in
> apply of InternalError, so you don't have to think about it later on.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/digital-asset/daml/pull/12906#discussion_r807779906>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGB4Z4H7SY77ML5PVMYHDM3U3N42FANCNFSM5OLDWI5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-16 11:11 UTC, ray-roestenburg-da commented
> I did that locally but the results were even less understandable code and the log logged less good... Maybe it is better to just hand around exceptions without throwing them as they automatically include the stack trace if I understand things correctly

`InternalError` and `ServerError` are handled differently in regards to logging, I think it makes sense how to create the message in the types itself (in various apply methods), so the code that decides that is close to the definition of the type. Not in the code handling the logging, or in (possibly many) places where you handle the error or want to make the error visible in some way. 

Another question is how an internal error arises out of a string we choose ourselves. If we choose the string, it would probably be a more specific error. Usually an InternalError means we give up and the reason is an (unexpected) Throwable?

2022-02-16 11:24 UTC, ray-roestenburg-da commented
@victormueller-da Formatting the error message nicely should not be too hard, you take the stacktrace, print it to a writer, and then append it to the msg. (this would also be very easy to test and iterate on to get it right in a simple unit test)

2022-02-28 12:46 UTC, realvictorprm commented
I think the best is to carry around throwables as the logger already supports good logging of exceptions. This would result in the simple error messages to be wrapped in an exception via making use of the apply methods.

2022-02-28 17:33 UTC, S11001001 approved these changes

2022-03-01 10:25 UTC, ray-roestenburg-da approved these changes

2022-03-09 12:43 UTC, merged