explore consequence of more aggressive ANF
digital-asset/daml pull request #14259
Opened 2022-06-23 12:27 UTC by nickchapman-da

Exactly which tests fails?
How much simpler wold the engine code be?

2022-09-28 13:12 UTC, akrmn approved these changes
Very nice simplification, thank you!

2022-09-28 14:21 UTC, remyhaemmerle-da requested changes
Unfortunately, we cannot go with this simplification right now:

- For validation we rely on determinism, we need all engine to reevaluate in the exact same in different versions of the engine. Using exception one can design a program that build 2 different transaction.
- Are we sure evaluate the function after its argument is not too disturbing for user ?
- Such change need a extensive CHANGLOG_ENTRY and should be approve by product.

2022-09-28 14:25 UTC, nickchapman-da commented
> Unfortunately, we cannot go with this simplification right now:
> 
> * For validation we rely on determinism, we need all engine to reevaluate in the exact same in different versions of the engine. Using exception one can design a program that build 2 different transaction.
> * Are we sure evaluate the function after its argument is not too disturbing for user ?
> * Such change need a extensive CHANGLOG_ENTRY
> * such change should be approved by product.

Of course. I realise all this.
This PR is simply to provide a clear summary of the benefits and consequences.
I shall move it back to draft status.

2022-09-28 14:31 UTC, nickchapman-da commented
> * Are we sure evaluate the function after its argument is not too disturbing for user ?
I am sure

2022-09-28 16:44 UTC, remyhaemmerle-da commented
> > * Are we sure evaluate the function after its argument is not too disturbing for user ?
> 
> I am sure

Will you be able to convince Bernhard ?   :laughing:

2022-09-29 09:10 UTC, nickchapman-da commented
> > > * Are we sure evaluate the function after its argument is not too disturbing for user ?
> > 
> > 
> > I am sure
> 
> Will you be able to convince Bernhard ? laughing

I would be more that interested it someone can present a realistic example where it makes any difference.

2022-09-29 11:20 UTC, remyhaemmerle-da commented
> I would be more that interested it someone can present a realistic example where it makes any difference.
The issue is that our costumers use a lot of "irrealistic" code.

2024-01-30 08:32 UTC, closed without merging

2024-01-30 08:33 UTC, remyhaemmerle-da commented
Implemented by @paulbrauner-da for Daml 3.x.
See #17253