release 2.3.1
digital-asset/daml pull request #14440
Opened 2022-07-15 17:33 UTC by garyverhaegen-da

Two very small bug fixes, as well as a new base image for the daml-sdk Docker image.

- #14434
- #14433
- #14437

CHANGELOG_BEGIN
CHANGELOG_END

2022-07-15 17:38 UTC, bame-da requested changes

2022-07-15 17:38 UTC, bame-da commented on LATEST
> +f529a2a0159e97aa8f74bff7794b07785fdda6c0 2.3.0 SPLIT_RELEASE
SHouldn't this be 2.3.1?

2022-07-15 17:41 UTC, bame-da approved these changes
thanks!

2022-07-15 19:08 UTC, merged

2022-07-18 14:37 UTC, stefanobaghino-da commented
Manual tests passed on Linux.