Adding missing content about Archiving in docs
digital-asset/daml pull request #16150
Opened 2023-01-25 12:41 UTC by da-katmurp

It seems strange for such a key concept to not have any info in docs so I wasn't surprised to find it in: /daml/intro/2_DamlScript.html. The problem is when key concepts are embedded in pages which are essentially about something completely different, they become impossible to find, don't come up in search, the forum fills up with questions, ..etc etc.

There is another issue with this page - and possibly others. It starts off by telling you what you're going to learn in a bulleted list. We are programmed to expect those bullets as headers on the page, and I see other pages in this section are behaving better on this. When those headers don't appear, it's confusing for the reader. 

**Suggest**: a full rewrite of this section by tech authors, also to make it easier to add and remove content by removing the numbering and pre/post-ambles.

This PR edits the info on https://docs.daml.com/daml/intro/2_DamlScript.html to be more succinct. 
Also, the archive function was missing from the reference so I added it there: /daml/reference/updates.html#archive

Requesting initial review and correctness edit from @leo-da who raised the ticket here: https://trello.com/c/EEET2z11/270-add-info-on-archiving

2023-01-25 18:15 UTC, loiskilberg-da commented
Added a docs ticket for rewriting this page as a separate task: https://trello.com/c/0DpkX6EU/279-improve-writing-on-this-page-daml-intro-2damlscripthtml

2023-01-25 18:16 UTC, loiskilberg-da approved these changes

2023-01-25 20:24 UTC, leonidr-da requested changes
Good start, added some clarifications.

2023-01-25 20:24 UTC, leonidr-da commented on docs/source/daml/reference/updates.rst
> +- Returns a transaction id on success.
```suggestion
- Returns unit.
```

2023-01-26 07:18 UTC, da-katmurp commented on docs/source/daml/reference/updates.rst
> +archive
ok, that's true

2023-01-26 07:26 UTC, da-katmurp commented
Accepted all suggestions. Added extra chunk about implicit Archive choice in `updates.rst`.

2023-02-01 15:11 UTC, leonidr-da approved these changes

2023-02-01 15:11 UTC, leonidr-da commented
@da-katmurp approved, thank you.

2023-02-01 16:30 UTC, merged