Remove duplicate HTTP metrics replaced by the golden signal metrics [PLEN-117]
digital-asset/daml pull request #16341
Opened 2023-02-17 15:02 UTC by nicu-da

2023-02-20 10:28 UTC, nicu-da commented
/azp run

2023-02-20 11:34 UTC, miklos-da approved these changes

2023-02-21 11:09 UTC, lucb-da requested changes
`httpRequestThroughput` should be removed too. It is covered by `requestsTotal`.

`commandSubmissionThroughput`, `uploadPackagesThroughput` and `allocatePartyThroughput` too. They are counters of specific requests, which can be filtered using the labels.

`uploadPackageTimer` is not referenced in the code base anymore, so it can go too.

2023-02-21 13:04 UTC, lucb-da approved these changes
LGTM

2023-02-21 13:04 UTC, da-katmurp approved these changes

2023-02-21 13:04 UTC, da-katmurp commented on docs/source/json-api/production-setup/metrics.rst
>  important to track.
```suggestion
In addition, see the following list of important metrics:
```

2023-02-21 13:04 UTC, da-katmurp commented on docs/source/json-api/production-setup/metrics.rst
>  A Counter. Count of active websocket connections
```suggestion
A Counter. Counts active websocket connections.
```

2023-02-22 12:42 UTC, nicu-da commented
@BryceStansfieldAt-da We're merging these changes as to not miss the 2.6 release cutoff, please feel free to post any comments and we'll address them in a different PR.

2023-02-22 12:42 UTC, merged

2023-02-23 05:46 UTC, BryceStansfieldAt-da commented
HI @nicu-da, after a bit of digging I can see where labels for the metrics are defined, and I can see that they're being hooked into Tasks somehow. But I can't find where the metrics are actually being recorded and how they're being sent off to prometheus. Would you be able to point me to that piece of code?

2023-02-23 10:08 UTC, nicu-da commented
> HI @nicu-da, after a bit of digging I can see where labels for the metrics are defined, and I can see that they're being hooked into Tasks somehow. But I can't find where the metrics are actually being recorded and how they're being sent off to prometheus. Would you be able to point me to that piece of code?

@BryceStansfieldAt-da Here is where all the magic for hooking up to prometheus happens https://github.com/digital-asset/daml/blob/main/ledger-service/metrics/src/main/scala/com/digitalasset/metrics/api/reporters/MetricsReporting.scala