Updated oracle image to 19.18
digital-asset/daml pull request #16704
Opened 2023-04-17 11:42 UTC by daravep

2023-04-17 12:01 UTC, garyverhaegen-da commented
Since the last Oracle update broke the daily compat test, I'm going to start a compat test on this branch. Please don't merge until it's finished running (and hopefully succeeded). Note that we generally don't run compat tests on PRs so they're not blocking at the GitHub level (i.e. "please don't set auto-merge").

2023-04-17 12:02 UTC, garyverhaegen-da commented
See details [here](https://dev.azure.com/digitalasset/daml/_build/results?buildId=139451&view=results).

2023-04-17 15:30 UTC, garyverhaegen-da requested changes
Looks like this breaks the Oracle migrations test again.

2023-04-18 07:33 UTC, closed without merging

2023-04-18 07:34 UTC, daravep commented
Booh. Though it's a bit frightening that our Oracle tests fail after upgrading Oracle ...

2023-04-18 08:02 UTC, garyverhaegen-da commented
> Booh. Though it's a bit frightening that our Oracle tests fail after upgrading Oracle ... But now I understand and will leave it to @mziolekda to see whether he can / want to upgrade Oracle.

I have no idea what those tests do. You're very welcome to take a closer look if you want, though I'm afraid I have no pointers to offer.