ledger-api-client: Rename `maxInboundMessageSize` to `maxInboundMetadataSize`.
digital-asset/daml pull request #7290
Opened 2020-09-01 08:57 UTC by SamirTalwar-DA

### Changelog

- **[Scala Bindings]** Rename a field in the `LedgerClientConfiguration` to `maxInboundMetadataSize`, to match the builder Netty channel builder. It was incorrectly named `maxInboundMessageSize`, which is a different channel property that configures the maximum message size, not the header size.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2020-09-01 11:30 UTC, stefanobaghino-da requested changes
Having a look at [this commit](https://github.com/digital-asset/daml/commit/d6fc2bbb58583b2816d79554bdd7c7cd3ff44ce8) it appears that the actual fix should be to use the proper method, rather than renaming the configuration option.

2020-09-01 13:05 UTC, SamirTalwar-DA commented
I don't know what you mean, @stefanobaghino-da. I think the issue was that I copied the wrong name from the `GrpcServer.Owner` class, not that the method call is wrong.

On the client side, gRPC errors are sent as part of the headers, not the body, so this field makes the header size configurable to make it possible to send a larger error message.

2020-09-01 13:13 UTC, stefanobaghino-da commented
> I don't know what you mean, @stefanobaghino-da. I think the issue was that I copied the wrong name from the `GrpcServer.Owner` class, not that the method call is wrong.
> 
> On the client side, gRPC errors are sent as part of the headers, not the body, so this field makes the header size configurable to make it possible to send a larger error message.

Then I would suggest you add a further option. We need to be able to set the message size.

2020-09-01 13:16 UTC, SamirTalwar-DA commented
Agreed. It turns out people already do this by passing an already-configured builder to `LedgerClient.fromBuilder`, which is how I discovered that there was an issue here. I wanted to fix the problem before introducing a new feature.

2020-09-01 14:58 UTC, stefanobaghino-da commented
The fix is so small and easy that I think it's fine to have them both in the same PR. Furthermore, I'd prefer if we could try to maintain the discipline to not break the API if we don't have to (which in Scala also means parameter names).

2020-09-01 15:00 UTC, SamirTalwar-DA commented
OK, cool, I'll get it in.

2020-09-01 20:37 UTC, leo-da commented
json-api changes look good. Thanks!

2020-09-02 07:38 UTC, stefanobaghino-da approved these changes
Looks excellent to me. 🙂

2020-09-02 08:41 UTC, merged