Replace occurrances of DAML SDK in the docs with appropriate new terms
digital-asset/daml pull request #7739
Opened 2020-10-19 14:27 UTC by bame-da

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2020-10-19 16:52 UTC, cocreature requested changes
Mostly looks good to me but this needs some page that explains the relationship between DAML connect and SDK. Otherwise this is just very confusing to users

2020-10-19 16:52 UTC, cocreature commented on docs/configs/pdf/index.rst
> +   Installing DAML Connect <getting-started/installation>
Given that we renamed the thing installed by the assistant to "DAML SDK", I think this should also be DAML SDK.

2020-10-21 09:23 UTC, bame-da commented on docs/configs/pdf/index.rst
> +   Installing DAML Connect <getting-started/installation>
Fair enough.

```suggestion
   Installing the SDK <getting-started/installation>
```

2020-10-21 09:24 UTC, bame-da commented on docs/source/index.rst
> +   Installing DAML Connect <getting-started/installation>
```suggestion
   Installing the SDK <getting-started/installation>
```

2020-10-21 09:27 UTC, bame-da commented
> Mostly looks good to me but this needs some page that explains the relationship between DAML connect and SDK. Otherwise this is just very confusing to users

Fully agree. A second PR with an explanation of what DAML Connect is will follow. Just doing this piecemeal to keep PRs managable. This is the pure renaming PR.

2020-10-21 09:31 UTC, cocreature commented
> Fully agree. A second PR with an explanation of what DAML Connect is will follow. Just doing this piecemeal to keep PRs managable. This is the pure renaming PR.

Fair enough, I’m generally not super fond of splitting up PRs if it introduces inconsistencies (master should always be releasable) but I’ll trust you that you can get the change in before 1.7 :slightly_smiling_face:

2020-10-21 09:32 UTC, cocreature approved these changes
Thanks!

2020-10-21 12:03 UTC, merged