Ledger: refactor bazel packaging of tedger test tool
digital-asset/daml pull request #8894
Opened 2021-02-18 10:31 UTC by remyhaemmerle-da

improve previous generalization from #8695

- use lf version instead keyword (like 'stable', 'latest', 'dev') to
  tag actual target.  This will allow two keywords to map to the same
  versions without doing twice the compilation/test work.

- use alias to map keywords tag target to versioned tag target.

- extend lookup logic to find test common dar.

- move package manage dar to test_commong.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2021-02-18 15:32 UTC, remyhaemmerle-da commented on ledger-service/http-json/BUILD.bazel
> +        "//ledger/test-common:test-dars-stable",
```suggestion
        "//ledger/test-common:model-tests-stable.dar",
```

2021-02-18 17:14 UTC, remyhaemmerle-da commented on language-support/java/codegen/src/ledger-tests/scala/com/digitalasset/TestUtil.scala
> +  def testDalf: File =
```suggestion
  def testDalf =
```

2021-02-18 17:14 UTC, remyhaemmerle-da commented on language-support/java/codegen/src/ledger-tests/scala/com/digitalasset/TestUtil.scala
> +
```suggestion
```

2021-02-18 19:41 UTC, remyhaemmerle-da commented on rules_daml/daml.bzl
> +        project_name = project_name or name,
:copyright: @cocreature

2021-02-18 20:41 UTC, cocreature approved these changes
Thanks!

2021-02-18 20:41 UTC, cocreature commented on compiler/damlc/tests/BUILD.bazel
> +load("//ledger/test-common:test-common.bzl", "test_common_configurations", "test_common_lf_targets")
where are you using the new imports?

2021-02-18 20:41 UTC, cocreature commented on daml-script/dump/BUILD.bazel
> +        "//ledger/test-common:test-dars-stable",
is it worth having an alias that defaults to the stable version?

2021-02-18 20:41 UTC, cocreature commented on ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/suites/PackageManagementServiceIT.scala
> +      val in = getClass.getClassLoader.getResourceAsStream(testPackageResourcePath)
why do we need to throw a `getClassLoader` in between now?

2021-02-18 20:41 UTC, cocreature commented on ledger/test-common/BUILD.bazel
> +            name = "%s-%s%s" % (target_prefix, name, target_suffix),
it’s hard to see what is actually being aliased here quickly. I think a comment for future readers would be helpful with an example.

2021-02-19 09:14 UTC, aherrmann-da approved these changes

2021-02-19 16:10 UTC, gerolf-da approved these changes
Thanks @remyhaemmerle-da

2021-02-19 16:51 UTC, miklos-da requested changes

2021-02-19 16:51 UTC, miklos-da commented on ledger/test-common/BUILD.bazel
> +package com.daml.ledger.test_common
Please follow the [Java package naming conventions](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names), i.e., don't use underscores. If you don't want to end up with `testcommon`, then please create a package `com.daml.ledger.test.common` or similar.

2021-02-22 09:42 UTC, miklos-da approved these changes

2021-02-22 10:41 UTC, merged