Distinct before fetching parties in allocateMissingInformees
digital-asset/daml pull request #8907
Opened 2021-02-22 09:34 UTC by tudor-da

This PR addresses an issue where a rich submission with a significant number of non-distinct informees causes an PostgreSQL JDBC exception when allocating missing informees. 

`sandbox_1        | WARN: daml.index.db.connection.sandbox - Connection org.postgresql.jdbc.PgConnection@79adebf8 marked as broken because of SQLSTATE(08006), ErrorCode(0)
sandbox_1        | org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
sandbox_1        |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:350)
sandbox_1        |      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
...
sandbox_1        |      at com.daml.platform.store.dao.JdbcLedgerDao$.selectParties(JdbcLedgerDao.scala:1052)
sandbox_1        |      at com.daml.platform.store.dao.JdbcLedgerDao.$anonfun$getParties$1(JdbcLedgerDao.scala:635)
sandbox_1        |      at com.daml.platform.store.dao.HikariJdbcConnectionProvider.$anonfun$runSQL$1(HikariJdbcConnectionProvider.scala:148)
...
sandbox_1        | Caused by: java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 74374
sandbox_1        |      at org.postgresql.core.PGStream.sendInteger2(PGStream.java:347)
sandbox_1        |      at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1547)
sandbox_1        |      at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1872)
sandbox_1        |      at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1433)
sandbox_1        |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:315)
sandbox_1        |      ... 50 common frames omitted`

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2021-02-23 08:12 UTC, mziolekda requested changes
It looks good. Could you also provide test cases for following corner cases:
- implicit party allocation turned off
- all parties known already
- write service fails to allocate party

2021-02-23 15:10 UTC, tudor-da commented
> It looks good. Could you also provide test cases for following corner cases:
> 
>     * implicit party allocation turned off
> 
>     * all parties known already
> 
>     * write service fails to allocate party

@mziolekda Done

2021-02-23 16:03 UTC, tudor-da commented
/run azp

2021-02-23 16:03 UTC, tudor-da commented
/azp run

2021-02-23 16:04 UTC, tudor-da commented
\azp run

2021-02-24 10:33 UTC, mziolekda approved these changes
Looks good, thanks

2021-02-24 10:33 UTC, merged

2021-02-24 10:43 UTC, gerolf-da commented
🎉