Streaming contract state events [DPP-304
digital-asset/daml pull request #9314
Opened 2021-03-31 17:58 UTC by kamil-da

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

2021-04-01 12:07 UTC, kamil-da commented on ledger/participant-integration-api/src/main/scala/platform/store/appendonlydao/JdbcLedgerDao.scala
> +
I wasn't sure on the strategy for the mutable state cache vs parallel ingestion development.
@nmarton-da @tudor-da Which package is appropriate for the mutable state cache work - `dao` or `appendonlydao`?

2021-04-01 12:07 UTC, kamil-da commented on ledger/participant-integration-api/src/main/scala/platform/store/appendonlydao/events/TransactionsReader.scala
> +
The same as above.

2021-04-07 05:58 UTC, tudor-da requested changes

2021-04-07 09:45 UTC, kamil-da commented on ledger/metrics/src/main/scala/com/daml/metrics/Metrics.scala
> +          "get_contract_lifecycle_events"
Fixed.

2021-04-07 09:45 UTC, kamil-da commented on ledger/participant-integration-api/src/main/scala/platform/store/dao/LedgerDao.scala
> +  // TODO: move this method to a separate *Reader
You're right. I've deleted the comment.

2021-04-07 09:45 UTC, kamil-da commented on ledger/participant-integration-api/src/main/scala/platform/store/dao/MeteredLedgerDao.scala
> +  ): Future[(Offset, Long)] = ledgerDao.lookupLedgerEndAndEventSequentialId()
Done.

2021-04-07 09:47 UTC, kamil-da commented on ledger/participant-integration-api/src/main/scala/platform/store/dao/ParametersTable.scala
> +  // THE SEQUENTIAL ID IS GOING TO BE INTRODUCED AS A PART OF THE APPEND-ONLY SCHEMA
Currently my changes are integrated in the base `dao` package. Do I understand correctly that there is no need to integrate them with `appendonlydao` package for now?

2021-04-08 17:39 UTC, closed without merging